Update gradio_client version in requirements.txt
The gradio_client version specified in the requirements is not compatible with the gradio version. I initially got the error: 

`
ERROR: Cannot install -r requirements.txt (line 4) and gradio_client==0.7.1 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested gradio_client==0.7.1
    gradio 4.11.0 depends on gradio-client==0.7.3
`